name: PRs reviews reminder

on:
  schedule:
    - cron: "0 8-17/1 * * 1-5"
  workflow_dispatch:

jobs:
  pr-reviews-reminder:
    runs-on: ubuntu-latest
    steps:
    - uses: Aniket-Engg/pr-reviews-reminder-action@discUpd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
